### PR TITLE
READY : Fixed branching in test routine `startSingleOptionDry` & removed spaces after `if`.

### PR DESCRIPTION
**Pull request by JackieJoo**

### CODE REVIEW

**Comment by Wandalen** [comment]
Fix styles.

**Comment by JackieJoo** [comment]
> Fix styles, please

Fixed

**Comment by Wandalen** [comment]
whole file

**Comment by JackieJoo** [comment]
> whole file

Fixed

**Comment by Wandalen** [comment]
whole file!

**Pull request merged**
